services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: expreezmeal-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - cloudflare-prod-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: expreezmeal-frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cloudflare-prod-net
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: expreezmeal-redis
    ports:
      - "6379:6379"
    networks:
      - cloudflare-prod-net
    restart: unless-stopped

  database:
    image: postgres:alpine
    container_name: expreezmeal-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expreezmeal
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cloudflare-prod-net
    restart: unless-stopped


networks:
  cloudflare-prod-net:
    external: true

volumes:
  db_data: