services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: expreezmeal-backend-dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: expreezmeal-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: expreezmeal-database-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expreezmeal
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
    # restart: unless-stopped

  redis:
    image: redis:latest
    container_name: expreezmeal-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  db_data: