apiVersion: v1
kind: Service
metadata:
  name: expreezmeal-frontend-service
  namespace: dev-namespace
spec:
  selector:
    app: expreezmeal-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30002
  type: NodePort