"""Add customization tables

Revision ID: ce083773fb7f
Revises: 9be8fcd46a3d
Create Date: 2025-08-03 20:27:32.313214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce083773fb7f'
down_revision = '9be8fcd46a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_choices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customization_option_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_modifier', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customization_option_id'], ['customization_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_customizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=True),
    sa.Column('customization_option_id', sa.String(length=36), nullable=True),
    sa.Column('option_choice_id', sa.String(length=36), nullable=True),
    sa.Column('price_modifier', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customization_option_id'], ['customization_options.id'], ),
    sa.ForeignKeyConstraint(['option_choice_id'], ['option_choices.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_customizations')
    op.drop_table('option_choices')
    op.drop_table('customization_options')
    # ### end Alembic commands ###
